use port_management
GO

-- part 2
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED -- solution
BEGIN TRAN
SELECT * FROM Client
WAITFOR DELAY '00:00:06'
SELECT * FROM Client
COMMIT TRAN