use port_management
GO

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
-- SET TRANSACTION ISOLATION LEVEL REPEATABLE READ -- solution
BEGIN TRAN 
SELECT * FROM Client where id = 21
WAITFOR DELAY '00:00:07'
SELECT * FROM Client where id = 21
COMMIT TRAN