# Generated by Django 5.0.3 on 2024-04-16 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bird_api.bird')),
            ],
        ),
    ]
