# Generated by Django 5.0.3 on 2024-04-17 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird_api', '0002_nest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nest',
            name='bird',
        ),
        migrations.AddField(
            model_name='bird',
            name='nest_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bird_api.nest'),
        ),
    ]
