# Generated by Django 5.0.3 on 2024-05-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bird_api', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
